// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkO40jtBh36jiWJgYWEXLGxX_QM1D4V7I',
    appId: '1:730249119733:web:eb359b77326c834d16c2bc',
    messagingSenderId: '730249119733',
    projectId: 'pinnacleapptt',
    authDomain: 'pinnacleapptt.firebaseapp.com',
    storageBucket: 'pinnacleapptt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBML926Axuq6mQzbacxFppWrDv7jizmrU',
    appId: '1:730249119733:android:8fb40c22879d3b1816c2bc',
    messagingSenderId: '730249119733',
    projectId: 'pinnacleapptt',
    storageBucket: 'pinnacleapptt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQSPLXd4XQ3paAeiCfjfO6kum4Q_q6LM',
    appId: '1:730249119733:ios:93964f4c16cab08b16c2bc',
    messagingSenderId: '730249119733',
    projectId: 'pinnacleapptt',
    storageBucket: 'pinnacleapptt.firebasestorage.app',
    iosBundleId: 'com.example.pinnacleapptt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQSPLXd4XQ3paAeiCfjfO6kum4Q_q6LM',
    appId: '1:730249119733:ios:93964f4c16cab08b16c2bc',
    messagingSenderId: '730249119733',
    projectId: 'pinnacleapptt',
    storageBucket: 'pinnacleapptt.firebasestorage.app',
    iosBundleId: 'com.example.pinnacleapptt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkO40jtBh36jiWJgYWEXLGxX_QM1D4V7I',
    appId: '1:730249119733:web:14f5c9401e406a4616c2bc',
    messagingSenderId: '730249119733',
    projectId: 'pinnacleapptt',
    authDomain: 'pinnacleapptt.firebaseapp.com',
    storageBucket: 'pinnacleapptt.firebasestorage.app',
  );
}
